pool: AgentDemo

strategy:
  matrix:
    node_11_x:
      node_version: 11.x
  maxParallel: 5

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '11.0'
  displayName: 'Install Node.js'

- script: |
    npm install && npm run test:report && npm run unit:junit
  displayName: 'npm install and test'
  continueOnError: true

- task: PublishTestResults@2
  displayName: "Publish Test Results"
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: "**test/junit-testresults.xml"
    testRunTitle: TestRun ${{ parameters.name }} $(node_version)
